export const ACTIONS = {
  LOAD_PRODUCTS_BEGIN: 'LOAD_PRODUCTS_BEGIN',
  FETCH_PRODUCTS_ERROR: 'FETCH_PRODUCTS_ERROR',
  FETCH_PRODUCTS_SUCCESS: 'FETCH_PRODUCTS_SUCCESS',
  OPEN_MODAL: 'OPEN_MODAL',
  CLOSE_MODAL: 'CLOSE_MODAL',
  LOAD_SINGLE_PRODUCT: 'LOAD_SINGLE_PRODUCT',
  SINGLE_PRODUCT_ERROR: 'SINGLE_PRODUCT_ERROR',
  FETCH_SINGLE_PRODUCT: 'FETCH_SINGLE_PRODUCT',
  UPDATE_SORT: 'UPDATE_SORT'
}